name: AkarianAuctionHouse
version: 0.0.6
main: net.akarian.auctionhouse.AuctionHouse
api-version: 1.19
description: Akarian Group's Auction House plugin.
author: Austin/KaYoz
database: true
depend:
  - Vault
commands:
  auctionhouse:
    description: Main AuctionHouse command.
    aliases:
      - ah
      - ahouse
      - auction
permissions:
  auctionhouse.help:
    description: AuctionHouse help command.
    default: true
  auctionhouse.admin:
    default: op
    description: AuctionHouse Admin command.
  auctionhouse.list:
    default: false
    description: AuctionHouse List command.

